### ISSUE TITLE
Airtable script無法偵測Guests table資料更新

### ISSUE THREAD

**Issue by chihhhhhao** [watchout-tw/watchout-battle#10]
Why 😢

**Comment by chihhhhhao** [comment]
40b002b5731b030d2a270e36cfdc9e933e2c5d0f：更改現有項目（1-10）的資料（新體育署長→體育署長），script會偵測到更新，但新增項目，script就偵測不到。

**Comment by wesley100002001** [comment]
問題出在一開始筆數很少，我拿到的 curl 的網址是有設定 MaxRecord=10

**Comment by wesley100002001** [comment]
Solved, and pull request created in `5d7f69a`
